In [1]:
import pandas

pandas.options.display.max_columns=999
pandas.options.display.max_rows=150

In [2]:
DST_CORE = pandas.read_csv('data/source-data/cryptic1-dst.csv')
DST_CORE.set_index('UNIQUEID', inplace=True)

MUTATIONS_CORE = pandas.read_csv('data/source-data/cryptic1-mutations.csv')
MUTATIONS_CORE.set_index('UNIQUEID', inplace=True)
samples_with_mutations=set(MUTATIONS_CORE.index)

DST_CORE.loc[DST_CORE.index.isin(samples_with_mutations), 'HAS_MUTATION']=True
DST_CORE.HAS_MUTATION.fillna(False,inplace=True)
DST_CORE.HAS_MUTATION.value_counts()

False    15991
True      6851
Name: HAS_MUTATION, dtype: int64

In [3]:
DST_CORE[:3]

,DRUG,SOURCE,METHOD_1,METHOD_2,METHOD_3,METHOD_CC,METHOD_MIC,PHENOTYPE,HAS_MUTATION
UNIQUEID,,,,,,,,,
site.24.subj.PT-2.lab.1997-606.iso.1,PZA,SEQTREAT2020,liquid media,MGIT,BACTEC460,100.0,NaN,S,False
site.24.subj.PT-4.lab.1998-151.iso.1,PZA,SEQTREAT2020,liquid media,MGIT,BACTEC460,100.0,NaN,S,False
site.24.subj.PT-5.lab.1998-713.iso.1,PZA,SEQTREAT2020,liquid media,MGIT,BACTEC460,100.0,NaN,S,False

In [4]:
GENOMES = pandas.read_pickle('~/focus/cryptic/cryptic-tables/GENOMES.pkl.gz')
GENOMES[:3]

,SITEID,SUBJID,LABID,ISOLATENO,SEQREPS,BELONGS_GPI,PER_SAMPLE_VCF_PRESENT,REGENOTYPED_VCF_PRESENT,CLOCKWORK_VERSION,TBI_INDEX,KMER_COUNTS,SNP_DISTANCE_TO_H37rV,SPECIES,LINEAGE_NAME,SUBLINEAGE_NAME,LINEAGE_PERCENTAGE,N_NULL,N_SNP,N_INDEL,N_FILTER_FAIL,N_REF,N_HET,CATALOGUE_NAME,CATALOGUE_VERSION,TB_TYPE_1,WGS_PREDICTION_STRING,IMAGE_MD5SUM,FTP_PATH,FTP_FILENAME_VCF,TREE_PATH,TREE_FILENAME_VCF,FASTQ_MD5SUMS,SEQTREAT_SAMPLE,MYKROBE_LINEAGE_NAME_1,MYKROBE_LINEAGE_NAME_2,ENA
UNIQUEID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
site.02.subj.0958.lab.22A197.iso.1,02,0958,22A197,1,197,True,True,True,0.8.3,True,False,1154.0,M. tuberculosis,Lineage 2,,71.283784,4934,0,1154,104,0,14329,CRyPTIC,v1.31,MDR,RRURRRSSSSSSSSS,{'02-0958-22A197-1-14': 'a587bac9ad2a0ebd36274...,/well/bag/jeffk/release_staging/,00/01/41/00/14100/site.02.iso.1.subject.0958.l...,dat/CRyPTIC2/V2/02/0958/22A197/1/regenotyped/,site.02.subj.0958.lab.22A197.iso.1.v0.8.3.rege...,,False,Lineage 2,lineage2.2.1,ERS5301054
site.02.subj.0823.lab.2013241494.iso.1,02,0823,2013241494,1,241494,True,True,True,0.8.3,True,False,388.0,M. tuberculosis,Lineage 4,,95.705521,2250,0,388,43,0,9442,CRyPTIC,v1.31,UNK,UUSUSSSSSSSSSSS,{'02-0823-2013241494-1-14': '698507bed7ff19268...,/well/bag/jeffk/release_staging/,00/01/41/43/14143/site.02.iso.1.subject.0823.l...,dat/CRyPTIC2/V2/02/0823/2013241494/1/regenotyped/,site.02.subj.0823.lab.2013241494.iso.1.v0.8.3....,,False,Lineage 2,lineage2.2.3,ERS5301097
site.02.subj.0359.lab.222018-14.iso.1,02,0359,222018-14,1,14222018,True,True,True,0.8.3,True,False,1147.0,M. tuberculosis,Lineage 2,,95.608108,3578,0,1147,118,0,13038,CRyPTIC,v1.31,UNK,SUSSSSSSUSSSSSS,{'02-0359-222018-14-1-14': '39c28529c7564ce379...,/well/bag/jeffk/release_staging/,00/01/08/73/10873/site.02.iso.1.subject.0359.l...,dat/CRyPTIC2/V2/02/0359/222018-14/1/regenotyped/,site.02.subj.0359.lab.222018-14.iso.1.v0.8.3.r...,,False,Lineage 2,lineage2.2.3,ERS5298526

In [5]:
MUTATIONS_CORE.reset_index(inplace=True)
MUTATIONS_CORE_COUNTS=MUTATIONS_CORE[['UNIQUEID','SITEID']].groupby('UNIQUEID').count()
MUTATIONS_CORE.set_index('UNIQUEID',inplace=True)
MUTATIONS_CORE_COUNTS.rename(columns={'SITEID':'N_MUTATIONS'},inplace=True)
MUTATIONS_CORE_COUNTS
MUTATIONS_CORE_COUNTS.N_MUTATIONS.value_counts()

1    6622
2     228
3       1
Name: N_MUTATIONS, dtype: int64

In [6]:
multi_mutation_samples = MUTATIONS_CORE_COUNTS[MUTATIONS_CORE_COUNTS.N_MUTATIONS>1].index
MUTATIONS_CORE[MUTATIONS_CORE.index.isin(multi_mutation_samples)].MUTATION.value_counts()

S65S         197
a-11g         18
398_indel      7
H57D           7
M175V          5
471_indel      5
V125F          4
a-15c          4
K96R           4
L4S            4
S74S           4
H51Q           4
V9G            4
A171T          4
T135P          3
T100A          3
L117L          3
g-21a          3
V139L          3
W68C           3
T100T          3
S67P           3
S67S           3
W119C          3
L120R          3
D12A           3
T168S          3
L182S          3
G132S          3
L85P           3
D63H           2
T142M          2
H82D           2
L35L           2
N11S           2
T76P           2
a-11c          2
T76I           2
A79V           2
L159R          2
Q10P           2
F13L           2
A143D          2
409_indel      2
V45M           2
Y103!          2
L27P           2
T160P          2
V21A           2
F94S           2
533_indel      2
H137Q          2
193_indel      2
V9V            2
K48T           2
G97D           2
Q141!          2
D136D          2
R121R          2
285_indel      2
P54L           2
K48N           1
V163A          1
85_indel       1
I31S           1
C14R           1
H43D           1
F94C           1
Q10!           1
Y103C          1
D49N           1
425_indel      1
A46T           1
T160A          1
T100I          1
A98V           1
Q141P          1
109_indel      1
P62L           1
467_indel      1
P69R           1
D145E          1
W68G           1
D136Y          1
431_indel      1
I6T            1
59_indel       1
H82R           1
P62T           1
t-12c          1
T47N           1
V163G          1
L4W            1
R176C          1
315_indel      1
P69S           1
F13V           1
G124D          1
c-3t           1
D49A           1
A161V          1
T100P          1
278_indel      1
I6L            1
21_indel       1
A98A           1
D49E           1
N11H           1
Q10H           1
T47I           1
T153P          1
S59C           1
G75G           1
R2P            1
I31T           1
M1T            1
K96T           1
-29_indel      1
Q122E          1
A171V          1
L159P          1
T76A           1
V7G            1
V139A          1
S18!           1
g-6c           1
K96E           1
L182W          1
C14G           1
G78S           1
448_indel      1
A134G          1
E174D          1
W119R          1
G101R          1
G108R          1
274_indel      1
H137N          1
C138R          1
Name: MUTATION, dtype: int64

In [74]:
lineages = GENOMES.loc[MUTATIONS_CORE.index.unique()][['MYKROBE_LINEAGE_NAME_1', 'MYKROBE_LINEAGE_NAME_2']]
lineages.to_csv('data/source-data/cryptic1-lineages.csv')
lineages

,MYKROBE_LINEAGE_NAME_1,MYKROBE_LINEAGE_NAME_2
UNIQUEID,,
site.05.subj.PSLM-0791.lab.SLM-049.iso.1,Lineage 4,lineage4.1.1.3
site.05.subj.LR-2032.lab.FN-00407-15.iso.1,Lineage 2,lineage2.2
site.05.subj.PMK-1015.lab.MK-1781.iso.1,Lineage 4,lineage4.3.4.2
site.05.subj.LR-2417.lab.FN-01304-17.iso.1,Lineage 4,lineage4.3.3
site.05.subj.LR-2162.lab.FN-00284-16.iso.1,Lineage 4,lineage4.3.3
...,...,...
site.10.subj.KD01666167.lab.KD01666167.iso.1,Lineage 4,lineage4.3.3
site.10.subj.YA00029870.lab.YA00029870.iso.1,Lineage 4,lineage4.4.1.1
site.10.subj.SABH00973542_S9.lab.BH00973542_S9.iso.1,Lineage 3,lineage3
site.10.subj.SADG00611914_S7.lab.DG00611914_S7.iso.1,Lineage 3,lineage3
site.10.subj.YA00008913.lab.YA00008913.iso.1,Lineage 1,lineage1.2.2

In [7]:
df2=MUTATIONS_CORE.join(GENOMES[['MYKROBE_LINEAGE_NAME_1', 'MYKROBE_LINEAGE_NAME_2']], how='left')

In [8]:
df2[['MYKROBE_LINEAGE_NAME_1','MYKROBE_LINEAGE_NAME_2']]

,MYKROBE_LINEAGE_NAME_1,MYKROBE_LINEAGE_NAME_2
UNIQUEID,,
site.00.subj.1000347.lab.H111540004.iso.1,Lineage 2,lineage2.2.10
site.00.subj.1000595.lab.H123460044.iso.1,Lineage 2,lineage2.2.9
site.00.subj.1004213.lab.H111060034.iso.1,Lineage 2,lineage2.2.6
site.00.subj.1004213.lab.H112000008.iso.1,Lineage 2,lineage2.2.6
site.00.subj.1004213.lab.H113100007.iso.1,Lineage 2,lineage2.2.6
...,...,...
site.ENA.subj.SAMN08892562.lab.1.iso.1,Lineage 3,lineage3
site.ENA.subj.SAMN08892566.lab.1.iso.1,Mixed,lineage3/lineage4.10
site.ENA.subj.SAMN08892575.lab.1.iso.1,Lineage 3,lineage3
site.ENA.subj.SAMN08892579.lab.1.iso.1,Lineage 3,lineage3
site.ENA.subj.SAMN08892579.lab.1.iso.1,Lineage 3,lineage3

In [9]:
df2[['MYKROBE_LINEAGE_NAME_1','MUTATION']].value_counts()

MYKROBE_LINEAGE_NAME_1  MUTATION
Lineage 3               S65S        2872
Lineage Bovis           H57D         188
Lineage 2               I6L          122
Lineage 4               Q10R          85
                        H51R          75
                                    ...
Lineage 3               W68G           1
Lineage 2               A143T          1
Lineage 3               W119R          1
                        W119C          1
Unknown                 S65S           1
Length: 707, dtype: int64

In [10]:
large_muts = df2.MUTATION.value_counts()[df2.MUTATION.value_counts()>=1].index

In [11]:
df3 = df2[df2.MUTATION.isin(large_muts) & df2.IS_SYNONYMOUS]
pandas.crosstab(df3.MUTATION,df3.MYKROBE_LINEAGE_NAME_1)

MYKROBE_LINEAGE_NAME_1,Lineage 1,Lineage 3,Lineage 4,Lineage 5,Lineage 6,Lineage Bovis,Mixed,Unknown
MUTATION,,,,,,,,
A165A,2,0,0,0,0,0,0,0
A25A,1,0,0,0,0,0,0,0
A30A,0,0,1,0,0,0,0,0
A38A,0,0,17,0,0,0,0,0
A98A,0,1,0,0,0,0,0,0
D136D,0,1,0,0,0,0,0,0
D63D,1,0,0,0,0,0,0,0
E181E,0,0,1,0,0,0,0,0
G108G,1,0,0,0,0,0,0,0
G113G,0,0,1,0,0,0,0,0
G17G,0,0,0,0,1,0,0,0
G24G,2,0,0,0,0,0,0,0
G75G,0,0,5,0,0,0,0,0
G97G,0,0,1,2,0,0,0,0
H43H,0,0,1,0,0,0,0,0
H82H,0,0,1,0,0,0,0,0
I31I,0,0,1,0,0,0,0,0
L117L,0,3,0,0,0,0,0,0
L151L,0,0,1,0,0,0,0,0
L172L,0,0,1,0,0,0,0,0
L19L,1,0,0,0,0,0,0,0
L35L,0,1,1,0,0,0,0,0
P77P,1,0,0,0,0,0,0,0
R140R,0,0,1,0,0,0,0,0
R148R,0,0,1,0,0,0,0,0
R2R,1,0,0,0,0,0,0,0
S65S,0,2872,0,0,0,0,21,1
S67S,0,2,0,0,0,0,0,0
S74S,0,0,0,0,0,1,0,0
T100T,0,2,0,0,0,0,0,0
T153T,0,0,2,0,0,0,0,0
T167T,0,0,1,0,0,0,0,0
V131V,1,0,0,0,0,0,0,0
V155V,1,0,0,0,0,0,0,0
V180V,0,0,1,0,0,0,0,0
V44V,0,0,1,0,0,0,1,0